type Movie = {
  id: number;
  title: string;
  year: number;
  genre: string[];
  imdbRating: number;
  poster: string;
  imageAlt: string;
  runtime: string;
};

export const moviesData: Movie[] = [
  {
    id: 1,
    title: "Inception",
    year: 2010,
    genre: ["Action", "Adventure", "Sci-Fi"],
    imdbRating: 8.8,
    poster: "",
    imageAlt: "Inception movie poster",
    runtime: "2h 28m",
  },
  {
    id: 2,
    title: "The Dark Knight",
    year: 2008,
    genre: ["Action", "Crime", "Drama"],
    imdbRating: 9.0,
    poster: "",
    imageAlt: "The Dark Knight movie poster",
    runtime: "2h 32m",
  },
  {
    id: 3,
    title: "Interstellar",
    year: 2014,
    genre: ["Adventure", "Drama", "Sci-Fi"],
    imdbRating: 8.6,
    poster: "",
    imageAlt: "Interstellar movie poster",
    runtime: "2h 49m",
  },
  {
    id: 4,
    title: "The Matrix",
    year: 1999,
    genre: ["Action", "Sci-Fi"],
    imdbRating: 8.7,
    poster: "",
    imageAlt: "The Matrix movie poster",
    runtime: "2h 16m",
  },
  {
    id: 5,
    title: "Gladiator",
    year: 2000,
    genre: ["Action", "Adventure", "Drama"],
    imdbRating: 8.5,
    poster: "",
    imageAlt: "Gladiator movie poster",
    runtime: "2h 35m",
  },
  {
    id: 6,
    title: "The Avengers",
    year: 2012,
    genre: ["Action", "Adventure", "Sci-Fi"],
    imdbRating: 8.0,
    poster: "",
    imageAlt: "The Avengers movie poster",
    runtime: "2h 23m",
  },
  {
    id: 7,
    title: "Guardians of the Galaxy",
    year: 2014,
    genre: ["Action", "Adventure", "Comedy"],
    imdbRating: 8.0,
    poster: "",
    imageAlt: "Guardians of the Galaxy movie poster",
    runtime: "2h 1m",
  },
  {
    id: 8,
    title: "Guardians of the Galaxy Vol. 2",
    year: 2017,
    genre: ["Action", "Adventure", "Comedy"],
    imdbRating: 7.6,
    poster: "",
    imageAlt: "Guardians of the Galaxy Vol. 2 movie poster",
    runtime: "2h 16m",
  },
  {
    id: 9,
    title: "Iron Man",
    year: 2008,
    genre: ["Action", "Adventure", "Sci-Fi"],
    imdbRating: 7.9,
    poster: "",
    imageAlt: "Iron Man movie poster",
    runtime: "2h 6m",
  },
  {
    id: 10,
    title: "Spider-Man: Homecoming",
    year: 2017,
    genre: ["Action", "Adventure", "Sci-Fi"],
    imdbRating: 7.4,
    poster: "",
    imageAlt: "Spider-Man: Homecoming movie poster",
    runtime: "2h 13m",
  },
  {
    id: 11,
    title: "Black Panther",
    year: 2018,
    genre: ["Action", "Adventure", "Sci-Fi"],
    imdbRating: 7.3,
    poster: "",
    imageAlt: "Black Panther movie poster",
    runtime: "2h 14m",
  },
  {
    id: 12,
    title: "Doctor Strange",
    year: 2016,
    genre: ["Action", "Adventure", "Fantasy"],
    imdbRating: 7.5,
    poster: "",
    imageAlt: "Doctor Strange movie poster",
    runtime: "1h 55m",
  },
  {
    id: 13,
    title: "Thor: Ragnarok",
    year: 2017,
    genre: ["Action", "Adventure", "Comedy"],
    imdbRating: 7.9,
    poster: "",
    imageAlt: "Thor: Ragnarok movie poster",
    runtime: "2h 10m",
  },
  {
    id: 14,
    title: "Ant-Man",
    year: 2015,
    genre: ["Action", "Adventure", "Comedy"],
    imdbRating: 7.3,
    poster: "",
    imageAlt: "Ant-Man movie poster",
    runtime: "1h 57m",
  },
  {
    id: 15,
    title: "Captain America: Civil War",
    year: 2016,
    genre: ["Action", "Adventure", "Sci-Fi"],
    imdbRating: 7.8,
    poster: "",
    imageAlt: "Captain America: Civil War movie poster",
    runtime: "2h 27m",
  },
  {
    id: 16,
    title: "Captain Marvel",
    year: 2019,
    genre: ["Action", "Adventure", "Sci-Fi"],
    imdbRating: 6.9,
    poster: "",
    imageAlt: "Captain Marvel movie poster",
    runtime: "2h 3m",
  },
  {
    id: 17,
    title: "Avengers: Infinity War",
    year: 2018,
    genre: ["Action", "Adventure", "Sci-Fi"],
    imdbRating: 8.4,
    poster: "",
    imageAlt: "Avengers: Infinity War movie poster",
    runtime: "2h 29m",
  },
  {
    id: 18,
    title: "Avengers: Endgame",
    year: 2019,
    genre: ["Action", "Adventure", "Drama"],
    imdbRating: 8.4,
    poster: "",
    imageAlt: "Avengers: Endgame movie poster",
    runtime: "3h 1m",
  },
  {
    id: 19,
    title: "Batman Begins",
    year: 2005,
    genre: ["Action", "Adventure"],
    imdbRating: 8.2,
    poster: "",
    imageAlt: "Batman Begins movie poster",
    runtime: "2h 20m",
  },
  {
    id: 20,
    title: "The Prestige",
    year: 2006,
    genre: ["Drama", "Mystery", "Sci-Fi"],
    imdbRating: 8.5,
    poster: "",
    imageAlt: "The Prestige movie poster",
    runtime: "2h 10m",
  },
  {
    id: 21,
    title: "Memento",
    year: 2000,
    genre: ["Mystery", "Thriller"],
    imdbRating: 8.4,
    poster: "",
    imageAlt: "Memento movie poster",
    runtime: "1h 53m",
  },
  {
    id: 22,
    title: "Dunkirk",
    year: 2017,
    genre: ["Action", "Drama", "History"],
    imdbRating: 7.9,
    poster: "",
    imageAlt: "Dunkirk movie poster",
    runtime: "1h 46m",
  },
  {
    id: 23,
    title: "Tenet",
    year: 2020,
    genre: ["Action", "Sci-Fi", "Thriller"],
    imdbRating: 7.4,
    poster: "",
    imageAlt: "Tenet movie poster",
    runtime: "2h 30m",
  },
  {
    id: 24,
    title: "Joker",
    year: 2019,
    genre: ["Crime", "Drama", "Thriller"],
    imdbRating: 8.5,
    poster: "",
    imageAlt: "Joker movie poster",
    runtime: "2h 2m",
  },
  {
    id: 25,
    title: "The Lion King",
    year: 1994,
    genre: ["Animation", "Adventure", "Drama"],
    imdbRating: 8.5,
    poster: "",
    imageAlt: "The Lion King movie poster",
    runtime: "1h 28m",
  },
  {
    id: 26,
    title: "Shrek",
    year: 2001,
    genre: ["Animation", "Adventure", "Comedy"],
    imdbRating: 7.8,
    poster: "",
    imageAlt: "Shrek movie poster",
    runtime: "1h 30m",
  },
  {
    id: 27,
    title: "Finding Nemo",
    year: 2003,
    genre: ["Animation", "Adventure", "Comedy"],
    imdbRating: 8.1,
    poster: "",
    imageAlt: "Finding Nemo movie poster",
    runtime: "1h 40m",
  },
  {
    id: 28,
    title: "Frozen",
    year: 2013,
    genre: ["Animation", "Adventure", "Comedy"],
    imdbRating: 7.4,
    poster: "",
    imageAlt: "Frozen movie poster",
    runtime: "1h 42m",
  },
  {
    id: 29,
    title: "Moana",
    year: 2016,
    genre: ["Animation", "Adventure", "Comedy"],
    imdbRating: 7.6,
    poster: "",
    imageAlt: "Moana movie poster",
    runtime: "1h 47m",
  },
  {
    id: 30,
    title: "Toy Story",
    year: 1995,
    genre: ["Animation", "Adventure", "Comedy"],
    imdbRating: 8.3,
    poster: "",
    imageAlt: "Toy Story movie poster",
    runtime: "1h 21m",
  },
  {
    id: 31,
    title: "Toy Story 2",
    year: 1999,
    genre: ["Animation", "Adventure", "Comedy"],
    imdbRating: 7.9,
    poster: "",
    imageAlt: "Toy Story 2 movie poster",
    runtime: "1h 32m",
  },
  {
    id: 32,
    title: "Toy Story 3",
    year: 2010,
    genre: ["Animation", "Adventure", "Comedy"],
    imdbRating: 8.3,
    poster: "",
    imageAlt: "Toy Story 3 movie poster",
    runtime: "1h 43m",
  },
  {
    id: 33,
    title: "Toy Story 4",
    year: 2019,
    genre: ["Animation", "Adventure", "Comedy"],
    imdbRating: 7.7,
    poster: "",
    imageAlt: "Toy Story 4 movie poster",
    runtime: "1h 40m",
  },
  {
    id: 34,
    title: "Coco",
    year: 2017,
    genre: ["Animation", "Adventure", "Comedy"],
    imdbRating: 8.4,
    poster: "",
    imageAlt: "Coco movie poster",
    runtime: "1h 45m",
  },
  {
    id: 35,
    title: "The Incredibles",
    year: 2004,
    genre: ["Animation", "Action", "Adventure"],
    imdbRating: 8.0,
    poster: "",
    imageAlt: "The Incredibles movie poster",
    runtime: "1h 55m",
  },
];
